# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IVpyqt5gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.JVcurves = QtWidgets.QWidget()
        self.JVcurves.setObjectName("JVcurves")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.JVcurves)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_JV = QtWidgets.QFrame(self.JVcurves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_JV.sizePolicy().hasHeightForWidth())
        self.frame_JV.setSizePolicy(sizePolicy)
        self.frame_JV.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_JV.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_JV.setObjectName("frame_JV")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_JV)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_JVMinY = QtWidgets.QDoubleSpinBox(self.frame_JV)
        self.doubleSpinBox_JVMinY.setObjectName("doubleSpinBox_JVMinY")
        self.gridLayout_4.addWidget(self.doubleSpinBox_JVMinY, 3, 3, 1, 1)
        self.pushButton_PlotJV = QtWidgets.QPushButton(self.frame_JV)
        self.pushButton_PlotJV.setObjectName("pushButton_PlotJV")
        self.gridLayout_4.addWidget(self.pushButton_PlotJV, 0, 3, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.frame_JV)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 4, 1, 1)
        self.doubleSpinBox_JVMaxX = QtWidgets.QDoubleSpinBox(self.frame_JV)
        self.doubleSpinBox_JVMaxX.setObjectName("doubleSpinBox_JVMaxX")
        self.gridLayout_4.addWidget(self.doubleSpinBox_JVMaxX, 3, 1, 1, 2)
        self.pushButton_SaveJV = QtWidgets.QPushButton(self.frame_JV)
        self.pushButton_SaveJV.setObjectName("pushButton_SaveJV")
        self.gridLayout_4.addWidget(self.pushButton_SaveJV, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.frame_JV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.pushButton_JVchangetitle = QtWidgets.QPushButton(self.frame_JV)
        self.pushButton_JVchangetitle.setObjectName("pushButton_JVchangetitle")
        self.gridLayout_4.addWidget(self.pushButton_JVchangetitle, 2, 0, 1, 3)
        self.doubleSpinBox_JVMinX = QtWidgets.QDoubleSpinBox(self.frame_JV)
        self.doubleSpinBox_JVMinX.setObjectName("doubleSpinBox_JVMinX")
        self.gridLayout_4.addWidget(self.doubleSpinBox_JVMinX, 3, 0, 1, 1)
        self.radioButton_JVoutside = QtWidgets.QRadioButton(self.frame_JV)
        self.radioButton_JVoutside.setObjectName("radioButton_JVoutside")
        self.gridLayout_4.addWidget(self.radioButton_JVoutside, 8, 0, 1, 2)
        self.spinBox_JVfontsize = QtWidgets.QSpinBox(self.frame_JV)
        self.spinBox_JVfontsize.setObjectName("spinBox_JVfontsize")
        self.gridLayout_4.addWidget(self.spinBox_JVfontsize, 2, 3, 1, 1)
        self.doubleSpinBox_JVMaxY = QtWidgets.QDoubleSpinBox(self.frame_JV)
        self.doubleSpinBox_JVMaxY.setObjectName("doubleSpinBox_JVMaxY")
        self.gridLayout_4.addWidget(self.doubleSpinBox_JVMaxY, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_JV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.frame_JV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_JV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 4, 1, 1)
        self.checkBox_JVLegend = QtWidgets.QCheckBox(self.frame_JV)
        self.checkBox_JVLegend.setObjectName("checkBox_JVLegend")
        self.gridLayout_4.addWidget(self.checkBox_JVLegend, 6, 0, 1, 1)
        self.pushButton_JVChangeLegend = QtWidgets.QPushButton(self.frame_JV)
        self.pushButton_JVChangeLegend.setObjectName("pushButton_JVChangeLegend")
        self.gridLayout_4.addWidget(self.pushButton_JVChangeLegend, 6, 2, 1, 2)
        self.radioButton_JVbottomleft = QtWidgets.QRadioButton(self.frame_JV)
        self.radioButton_JVbottomleft.setObjectName("radioButton_JVbottomleft")
        self.gridLayout_4.addWidget(self.radioButton_JVbottomleft, 8, 2, 1, 1)
        self.radioButton_JVbottomright = QtWidgets.QRadioButton(self.frame_JV)
        self.radioButton_JVbottomright.setObjectName("radioButton_JVbottomright")
        self.gridLayout_4.addWidget(self.radioButton_JVbottomright, 8, 3, 1, 1)
        self.radioButton_JVtoprigh = QtWidgets.QRadioButton(self.frame_JV)
        self.radioButton_JVtoprigh.setObjectName("radioButton_JVtoprigh")
        self.gridLayout_4.addWidget(self.radioButton_JVtoprigh, 7, 3, 1, 1)
        self.radioButton_JVtopleft = QtWidgets.QRadioButton(self.frame_JV)
        self.radioButton_JVtopleft.setObjectName("radioButton_JVtopleft")
        self.gridLayout_4.addWidget(self.radioButton_JVtopleft, 7, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_JV)
        self.widget_JVGraph = QtWidgets.QWidget(self.JVcurves)
        self.widget_JVGraph.setObjectName("widget_JVGraph")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_JVGraph)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3.addWidget(self.widget_JVGraph)
        self.tabWidget.addTab(self.JVcurves, "")
        self.MPPT = QtWidgets.QWidget()
        self.MPPT.setObjectName("MPPT")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MPPT)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_Mpp = QtWidgets.QFrame(self.MPPT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Mpp.sizePolicy().hasHeightForWidth())
        self.frame_Mpp.setSizePolicy(sizePolicy)
        self.frame_Mpp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Mpp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Mpp.setObjectName("frame_Mpp")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Mpp)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_Mpp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 5, 1, 1)
        self.pushButton_SaveMpp = QtWidgets.QPushButton(self.frame_Mpp)
        self.pushButton_SaveMpp.setObjectName("pushButton_SaveMpp")
        self.gridLayout.addWidget(self.pushButton_SaveMpp, 5, 0, 1, 2)
        self.checkBox_MppLegend = QtWidgets.QCheckBox(self.frame_Mpp)
        self.checkBox_MppLegend.setObjectName("checkBox_MppLegend")
        self.gridLayout.addWidget(self.checkBox_MppLegend, 6, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_Mpp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 4, 1, 1)
        self.spinBox_MppFontsize = QtWidgets.QSpinBox(self.frame_Mpp)
        self.spinBox_MppFontsize.setObjectName("spinBox_MppFontsize")
        self.gridLayout.addWidget(self.spinBox_MppFontsize, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_Mpp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 5, 1, 1)
        self.pushButton_MppchangeLegend = QtWidgets.QPushButton(self.frame_Mpp)
        self.pushButton_MppchangeLegend.setObjectName("pushButton_MppchangeLegend")
        self.gridLayout.addWidget(self.pushButton_MppchangeLegend, 5, 2, 1, 2)
        self.pushButton_MppChangeTitle = QtWidgets.QPushButton(self.frame_Mpp)
        self.pushButton_MppChangeTitle.setObjectName("pushButton_MppChangeTitle")
        self.gridLayout.addWidget(self.pushButton_MppChangeTitle, 5, 4, 1, 2)
        self.radioButton_MppTopleft = QtWidgets.QRadioButton(self.frame_Mpp)
        self.radioButton_MppTopleft.setObjectName("radioButton_MppTopleft")
        self.gridLayout.addWidget(self.radioButton_MppTopleft, 6, 2, 1, 1)
        self.doubleSpinBox_MaxY = QtWidgets.QDoubleSpinBox(self.frame_Mpp)
        self.doubleSpinBox_MaxY.setObjectName("doubleSpinBox_MaxY")
        self.gridLayout.addWidget(self.doubleSpinBox_MaxY, 2, 5, 1, 1)
        self.listWidget_MppSamples = QtWidgets.QListWidget(self.frame_Mpp)
        self.listWidget_MppSamples.setObjectName("listWidget_MppSamples")
        self.gridLayout.addWidget(self.listWidget_MppSamples, 0, 0, 5, 4)
        self.doubleSpinBox_MppMinX = QtWidgets.QDoubleSpinBox(self.frame_Mpp)
        self.doubleSpinBox_MppMinX.setObjectName("doubleSpinBox_MppMinX")
        self.gridLayout.addWidget(self.doubleSpinBox_MppMinX, 0, 4, 1, 1)
        self.doubleSpinBox_MppMaxX = QtWidgets.QDoubleSpinBox(self.frame_Mpp)
        self.doubleSpinBox_MppMaxX.setObjectName("doubleSpinBox_MppMaxX")
        self.gridLayout.addWidget(self.doubleSpinBox_MppMaxX, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_Mpp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 5, 1, 1)
        self.doubleSpinBox_MppMinY = QtWidgets.QDoubleSpinBox(self.frame_Mpp)
        self.doubleSpinBox_MppMinY.setObjectName("doubleSpinBox_MppMinY")
        self.gridLayout.addWidget(self.doubleSpinBox_MppMinY, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_Mpp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.radioButton_MppTopright = QtWidgets.QRadioButton(self.frame_Mpp)
        self.radioButton_MppTopright.setObjectName("radioButton_MppTopright")
        self.gridLayout.addWidget(self.radioButton_MppTopright, 6, 3, 1, 1)
        self.radioButton_MppBottomleft = QtWidgets.QRadioButton(self.frame_Mpp)
        self.radioButton_MppBottomleft.setObjectName("radioButton_MppBottomleft")
        self.gridLayout.addWidget(self.radioButton_MppBottomleft, 7, 2, 1, 1)
        self.radioButton_MppBottomright = QtWidgets.QRadioButton(self.frame_Mpp)
        self.radioButton_MppBottomright.setObjectName("radioButton_MppBottomright")
        self.gridLayout.addWidget(self.radioButton_MppBottomright, 7, 3, 1, 1)
        self.radioButton_MppOutside = QtWidgets.QRadioButton(self.frame_Mpp)
        self.radioButton_MppOutside.setObjectName("radioButton_MppOutside")
        self.gridLayout.addWidget(self.radioButton_MppOutside, 8, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_Mpp)
        self.widget_Mpp = QtWidgets.QWidget(self.MPPT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Mpp.sizePolicy().hasHeightForWidth())
        self.widget_Mpp.setSizePolicy(sizePolicy)
        self.widget_Mpp.setObjectName("widget_Mpp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Mpp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2.addWidget(self.widget_Mpp)
        self.widget_2 = QtWidgets.QWidget(self.MPPT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.tabWidget.addTab(self.MPPT, "")
        self.BoxPlot = QtWidgets.QWidget()
        self.BoxPlot.setObjectName("BoxPlot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.BoxPlot)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_BoxPlot = QtWidgets.QGroupBox(self.BoxPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_BoxPlot.sizePolicy().hasHeightForWidth())
        self.groupBox_BoxPlot.setSizePolicy(sizePolicy)
        self.groupBox_BoxPlot.setObjectName("groupBox_BoxPlot")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_BoxPlot)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_SaveBoxPlot = QtWidgets.QPushButton(self.groupBox_BoxPlot)
        self.pushButton_SaveBoxPlot.setObjectName("pushButton_SaveBoxPlot")
        self.gridLayout_6.addWidget(self.pushButton_SaveBoxPlot, 0, 0, 1, 1)
        self.checkBox_BoxPlotBig4 = QtWidgets.QCheckBox(self.groupBox_BoxPlot)
        self.checkBox_BoxPlotBig4.setObjectName("checkBox_BoxPlotBig4")
        self.gridLayout_6.addWidget(self.checkBox_BoxPlotBig4, 0, 1, 1, 1)
        self.checkBox_BoxPlotRevForw = QtWidgets.QCheckBox(self.groupBox_BoxPlot)
        self.checkBox_BoxPlotRevForw.setObjectName("checkBox_BoxPlotRevForw")
        self.gridLayout_6.addWidget(self.checkBox_BoxPlotRevForw, 0, 2, 1, 2)
        self.checkBox_BoxPlotBoxPlot = QtWidgets.QCheckBox(self.groupBox_BoxPlot)
        self.checkBox_BoxPlotBoxPlot.setObjectName("checkBox_BoxPlotBoxPlot")
        self.gridLayout_6.addWidget(self.checkBox_BoxPlotBoxPlot, 0, 4, 1, 1)
        self.spinBox_BoxPlotFontsize = QtWidgets.QSpinBox(self.groupBox_BoxPlot)
        self.spinBox_BoxPlotFontsize.setObjectName("spinBox_BoxPlotFontsize")
        self.gridLayout_6.addWidget(self.spinBox_BoxPlotFontsize, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_BoxPlot)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 6, 1, 1)
        self.comboBox_BoxPlotParam = QtWidgets.QComboBox(self.groupBox_BoxPlot)
        self.comboBox_BoxPlotParam.setObjectName("comboBox_BoxPlotParam")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.comboBox_BoxPlotParam.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_BoxPlotParam, 1, 0, 1, 1)
        self.checkBox_BoxPlotAftermpp = QtWidgets.QCheckBox(self.groupBox_BoxPlot)
        self.checkBox_BoxPlotAftermpp.setObjectName("checkBox_BoxPlotAftermpp")
        self.gridLayout_6.addWidget(self.checkBox_BoxPlotAftermpp, 1, 1, 1, 2)
        self.checkBox_BoxPlotBkg = QtWidgets.QCheckBox(self.groupBox_BoxPlot)
        self.checkBox_BoxPlotBkg.setObjectName("checkBox_BoxPlotBkg")
        self.gridLayout_6.addWidget(self.checkBox_BoxPlotBkg, 1, 3, 1, 2)
        self.spinBox_BoxPlotRotation = QtWidgets.QSpinBox(self.groupBox_BoxPlot)
        self.spinBox_BoxPlotRotation.setObjectName("spinBox_BoxPlotRotation")
        self.gridLayout_6.addWidget(self.spinBox_BoxPlotRotation, 1, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_BoxPlot)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 6, 1, 1)
        self.listWidget_BoxPlotGroup = QtWidgets.QListWidget(self.groupBox_BoxPlot)
        self.listWidget_BoxPlotGroup.setObjectName("listWidget_BoxPlotGroup")
        self.gridLayout_6.addWidget(self.listWidget_BoxPlotGroup, 2, 0, 1, 7)
        self.horizontalLayout_6.addWidget(self.groupBox_BoxPlot)
        self.widget_BoxPlot = QtWidgets.QWidget(self.BoxPlot)
        self.widget_BoxPlot.setObjectName("widget_BoxPlot")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_BoxPlot)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_6.addWidget(self.widget_BoxPlot)
        self.tabWidget.addTab(self.BoxPlot, "")
        self.TimeEvol = QtWidgets.QWidget()
        self.TimeEvol.setObjectName("TimeEvol")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.TimeEvol)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame = QtWidgets.QFrame(self.TimeEvol)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_PVPTime = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_PVPTime.sizePolicy().hasHeightForWidth())
        self.groupBox_PVPTime.setSizePolicy(sizePolicy)
        self.groupBox_PVPTime.setObjectName("groupBox_PVPTime")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_PVPTime)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_SavePVPTime = QtWidgets.QPushButton(self.groupBox_PVPTime)
        self.pushButton_SavePVPTime.setObjectName("pushButton_SavePVPTime")
        self.gridLayout_8.addWidget(self.pushButton_SavePVPTime, 0, 0, 1, 1)
        self.checkBox_PVPTimeLine = QtWidgets.QCheckBox(self.groupBox_PVPTime)
        self.checkBox_PVPTimeLine.setObjectName("checkBox_PVPTimeLine")
        self.gridLayout_8.addWidget(self.checkBox_PVPTimeLine, 0, 2, 1, 1)
        self.comboBox_PVPTimeParam = QtWidgets.QComboBox(self.groupBox_PVPTime)
        self.comboBox_PVPTimeParam.setObjectName("comboBox_PVPTimeParam")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.comboBox_PVPTimeParam.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_PVPTimeParam, 1, 0, 1, 1)
        self.checkBox_PVPTimeRelativeTime = QtWidgets.QCheckBox(self.groupBox_PVPTime)
        self.checkBox_PVPTimeRelativeTime.setObjectName("checkBox_PVPTimeRelativeTime")
        self.gridLayout_8.addWidget(self.checkBox_PVPTimeRelativeTime, 1, 1, 1, 2)
        self.checkBox_PVPTimeBig4 = QtWidgets.QCheckBox(self.groupBox_PVPTime)
        self.checkBox_PVPTimeBig4.setObjectName("checkBox_PVPTimeBig4")
        self.gridLayout_8.addWidget(self.checkBox_PVPTimeBig4, 0, 1, 1, 1)
        self.checkBox_PVPTimeNormal = QtWidgets.QCheckBox(self.groupBox_PVPTime)
        self.checkBox_PVPTimeNormal.setObjectName("checkBox_PVPTimeNormal")
        self.gridLayout_8.addWidget(self.checkBox_PVPTimeNormal, 0, 3, 1, 1)
        self.spinBox_PVPTimeNormalPoint = QtWidgets.QSpinBox(self.groupBox_PVPTime)
        self.spinBox_PVPTimeNormalPoint.setObjectName("spinBox_PVPTimeNormalPoint")
        self.gridLayout_8.addWidget(self.spinBox_PVPTimeNormalPoint, 1, 3, 1, 1)
        self.pushButton_PVPTimeLegend = QtWidgets.QPushButton(self.groupBox_PVPTime)
        self.pushButton_PVPTimeLegend.setObjectName("pushButton_PVPTimeLegend")
        self.gridLayout_8.addWidget(self.pushButton_PVPTimeLegend, 0, 4, 1, 1)
        self.pushButton_PVPTimePlot = QtWidgets.QPushButton(self.groupBox_PVPTime)
        self.pushButton_PVPTimePlot.setObjectName("pushButton_PVPTimePlot")
        self.gridLayout_8.addWidget(self.pushButton_PVPTimePlot, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_PVPTime)
        self.widget_PVPTime = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_PVPTime.sizePolicy().hasHeightForWidth())
        self.widget_PVPTime.setSizePolicy(sizePolicy)
        self.widget_PVPTime.setObjectName("widget_PVPTime")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_PVPTime)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2.addWidget(self.widget_PVPTime)
        self.horizontalLayout_7.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.TimeEvol)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_PVP = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_PVP.sizePolicy().hasHeightForWidth())
        self.groupBox_PVP.setSizePolicy(sizePolicy)
        self.groupBox_PVP.setObjectName("groupBox_PVP")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_PVP)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_SavePVPGraph = QtWidgets.QPushButton(self.groupBox_PVP)
        self.pushButton_SavePVPGraph.setObjectName("pushButton_SavePVPGraph")
        self.gridLayout_9.addWidget(self.pushButton_SavePVPGraph, 0, 0, 1, 1)
        self.comboBox_PVPx = QtWidgets.QComboBox(self.groupBox_PVP)
        self.comboBox_PVPx.setObjectName("comboBox_PVPx")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.comboBox_PVPx.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_PVPx, 0, 1, 1, 1)
        self.comboBox_PVPgroup = QtWidgets.QComboBox(self.groupBox_PVP)
        self.comboBox_PVPgroup.setObjectName("comboBox_PVPgroup")
        self.gridLayout_9.addWidget(self.comboBox_PVPgroup, 1, 0, 1, 1)
        self.comboBox_PVPy = QtWidgets.QComboBox(self.groupBox_PVP)
        self.comboBox_PVPy.setObjectName("comboBox_PVPy")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.comboBox_PVPy.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_PVPy, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_PVP)
        self.widget_PVPGraph = QtWidgets.QWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_PVPGraph.sizePolicy().hasHeightForWidth())
        self.widget_PVPGraph.setSizePolicy(sizePolicy)
        self.widget_PVPGraph.setObjectName("widget_PVPGraph")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_PVPGraph)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_3.addWidget(self.widget_PVPGraph)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.tabWidget.addTab(self.TimeEvol, "")
        self.Histogram = QtWidgets.QWidget()
        self.Histogram.setObjectName("Histogram")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Histogram)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_HistoGraph = QtWidgets.QGroupBox(self.Histogram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_HistoGraph.sizePolicy().hasHeightForWidth())
        self.groupBox_HistoGraph.setSizePolicy(sizePolicy)
        self.groupBox_HistoGraph.setObjectName("groupBox_HistoGraph")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_HistoGraph)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_SaveHistoGraph = QtWidgets.QPushButton(self.groupBox_HistoGraph)
        self.pushButton_SaveHistoGraph.setObjectName("pushButton_SaveHistoGraph")
        self.gridLayout_12.addWidget(self.pushButton_SaveHistoGraph, 0, 0, 1, 1)
        self.checkBox_HistoFit = QtWidgets.QCheckBox(self.groupBox_HistoGraph)
        self.checkBox_HistoFit.setObjectName("checkBox_HistoFit")
        self.gridLayout_12.addWidget(self.checkBox_HistoFit, 0, 1, 1, 1)
        self.spinBox_HistoBins = QtWidgets.QSpinBox(self.groupBox_HistoGraph)
        self.spinBox_HistoBins.setObjectName("spinBox_HistoBins")
        self.gridLayout_12.addWidget(self.spinBox_HistoBins, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_HistoGraph)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 0, 3, 1, 1)
        self.comboBox_HistoType = QtWidgets.QComboBox(self.groupBox_HistoGraph)
        self.comboBox_HistoType.setObjectName("comboBox_HistoType")
        self.comboBox_HistoType.addItem("")
        self.comboBox_HistoType.addItem("")
        self.comboBox_HistoType.addItem("")
        self.comboBox_HistoType.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_HistoType, 1, 0, 1, 1)
        self.comboBox_HistoScanDirect = QtWidgets.QComboBox(self.groupBox_HistoGraph)
        self.comboBox_HistoScanDirect.setObjectName("comboBox_HistoScanDirect")
        self.comboBox_HistoScanDirect.addItem("")
        self.comboBox_HistoScanDirect.addItem("")
        self.comboBox_HistoScanDirect.addItem("")
        self.comboBox_HistoScanDirect.addItem("")
        self.comboBox_HistoScanDirect.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_HistoScanDirect, 1, 1, 1, 2)
        self.comboBox_HistoParam = QtWidgets.QComboBox(self.groupBox_HistoGraph)
        self.comboBox_HistoParam.setObjectName("comboBox_HistoParam")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.comboBox_HistoParam.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_HistoParam, 1, 3, 1, 1)
        self.listWidget_HistoGroups = QtWidgets.QListWidget(self.groupBox_HistoGraph)
        self.listWidget_HistoGroups.setObjectName("listWidget_HistoGroups")
        self.gridLayout_12.addWidget(self.listWidget_HistoGroups, 2, 0, 1, 4)
        self.horizontalLayout_8.addWidget(self.groupBox_HistoGraph)
        self.widget_HistoGraph = QtWidgets.QWidget(self.Histogram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_HistoGraph.sizePolicy().hasHeightForWidth())
        self.widget_HistoGraph.setSizePolicy(sizePolicy)
        self.widget_HistoGraph.setObjectName("widget_HistoGraph")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_HistoGraph)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_8.addWidget(self.widget_HistoGraph)
        self.tabWidget.addTab(self.Histogram, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar_ImportData = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_ImportData.setProperty("value", 0)
        self.progressBar_ImportData.setObjectName("progressBar_ImportData")
        self.horizontalLayout_4.addWidget(self.progressBar_ImportData)
        self.pushButton_ImportData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ImportData.setObjectName("pushButton_ImportData")
        self.horizontalLayout_4.addWidget(self.pushButton_ImportData)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_DeleteRows = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_DeleteRows.setObjectName("pushButton_DeleteRows")
        self.horizontalLayout_5.addWidget(self.pushButton_DeleteRows)
        self.pushButton_DefineGroup = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_DefineGroup.setObjectName("pushButton_DefineGroup")
        self.horizontalLayout_5.addWidget(self.pushButton_DefineGroup)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.pushButton_AutoAnalysis = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AutoAnalysis.sizePolicy().hasHeightForWidth())
        self.pushButton_AutoAnalysis.setSizePolicy(sizePolicy)
        self.pushButton_AutoAnalysis.setObjectName("pushButton_AutoAnalysis")
        self.horizontalLayout.addWidget(self.pushButton_AutoAnalysis)
        self.verticalLayout.addWidget(self.frame_4)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 31))
        self.menubar.setObjectName("menubar")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_to_DB = QtWidgets.QAction(MainWindow)
        self.actionSave_to_DB.setObjectName("actionSave_to_DB")
        self.menuSession.addAction(self.actionLoad)
        self.menuSession.addAction(self.actionSave)
        self.menuDatabase.addAction(self.actionSave_to_DB)
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IVapp"))
        self.pushButton_PlotJV.setText(_translate("MainWindow", "Plot IV"))
        self.label_10.setText(_translate("MainWindow", "Fontsize"))
        self.pushButton_SaveJV.setText(_translate("MainWindow", "Save graph"))
        self.label_6.setText(_translate("MainWindow", "Min X"))
        self.pushButton_JVchangetitle.setText(_translate("MainWindow", "Change title"))
        self.radioButton_JVoutside.setText(_translate("MainWindow", "Outside"))
        self.label_7.setText(_translate("MainWindow", "Max X"))
        self.label_8.setText(_translate("MainWindow", "Min Y"))
        self.label_9.setText(_translate("MainWindow", "Max Y"))
        self.checkBox_JVLegend.setText(_translate("MainWindow", "Legend ?"))
        self.pushButton_JVChangeLegend.setText(_translate("MainWindow", "Change legend"))
        self.radioButton_JVbottomleft.setText(_translate("MainWindow", "Bottom Left"))
        self.radioButton_JVbottomright.setText(_translate("MainWindow", "Bottom Right"))
        self.radioButton_JVtoprigh.setText(_translate("MainWindow", "Top Right"))
        self.radioButton_JVtopleft.setText(_translate("MainWindow", "Top Left"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.JVcurves), _translate("MainWindow", "JV curves"))
        self.label_5.setText(_translate("MainWindow", "Set max Y"))
        self.pushButton_SaveMpp.setText(_translate("MainWindow", "Save graph"))
        self.checkBox_MppLegend.setText(_translate("MainWindow", "Legend ?"))
        self.label_4.setText(_translate("MainWindow", "Set min Y"))
        self.label.setText(_translate("MainWindow", "Fontsize"))
        self.pushButton_MppchangeLegend.setText(_translate("MainWindow", "Change legend"))
        self.pushButton_MppChangeTitle.setText(_translate("MainWindow", "Change title"))
        self.radioButton_MppTopleft.setText(_translate("MainWindow", "Top Left"))
        self.label_2.setText(_translate("MainWindow", "Set max X"))
        self.label_3.setText(_translate("MainWindow", "Set min X"))
        self.radioButton_MppTopright.setText(_translate("MainWindow", "Top Right"))
        self.radioButton_MppBottomleft.setText(_translate("MainWindow", "Bottom Left"))
        self.radioButton_MppBottomright.setText(_translate("MainWindow", "Bottom Right"))
        self.radioButton_MppOutside.setText(_translate("MainWindow", "Outside"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MPPT), _translate("MainWindow", "MPPT"))
        self.groupBox_BoxPlot.setTitle(_translate("MainWindow", "BoxPlot"))
        self.pushButton_SaveBoxPlot.setText(_translate("MainWindow", "Save graph"))
        self.checkBox_BoxPlotBig4.setText(_translate("MainWindow", "Big4"))
        self.checkBox_BoxPlotRevForw.setText(_translate("MainWindow", "RevForw"))
        self.checkBox_BoxPlotBoxPlot.setText(_translate("MainWindow", "BoxPlot"))
        self.label_11.setText(_translate("MainWindow", "Fontsize"))
        self.comboBox_BoxPlotParam.setItemText(0, _translate("MainWindow", "Eff"))
        self.comboBox_BoxPlotParam.setItemText(1, _translate("MainWindow", "FF"))
        self.comboBox_BoxPlotParam.setItemText(2, _translate("MainWindow", "Voc"))
        self.comboBox_BoxPlotParam.setItemText(3, _translate("MainWindow", "Jsc"))
        self.comboBox_BoxPlotParam.setItemText(4, _translate("MainWindow", "Vmpp"))
        self.comboBox_BoxPlotParam.setItemText(5, _translate("MainWindow", "Jmpp"))
        self.comboBox_BoxPlotParam.setItemText(6, _translate("MainWindow", "Pmpp"))
        self.comboBox_BoxPlotParam.setItemText(7, _translate("MainWindow", "Roc"))
        self.comboBox_BoxPlotParam.setItemText(8, _translate("MainWindow", "Rsc"))
        self.comboBox_BoxPlotParam.setItemText(9, _translate("MainWindow", "HI"))
        self.checkBox_BoxPlotAftermpp.setText(_translate("MainWindow", "Aftermpp"))
        self.checkBox_BoxPlotBkg.setText(_translate("MainWindow", "transparent bkg"))
        self.label_12.setText(_translate("MainWindow", "Rotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BoxPlot), _translate("MainWindow", "BoxPlot"))
        self.groupBox_PVPTime.setTitle(_translate("MainWindow", "Time Evolution"))
        self.pushButton_SavePVPTime.setText(_translate("MainWindow", "Save graph"))
        self.checkBox_PVPTimeLine.setText(_translate("MainWindow", "Line?"))
        self.comboBox_PVPTimeParam.setItemText(0, _translate("MainWindow", "Eff"))
        self.comboBox_PVPTimeParam.setItemText(1, _translate("MainWindow", "FF"))
        self.comboBox_PVPTimeParam.setItemText(2, _translate("MainWindow", "Voc"))
        self.comboBox_PVPTimeParam.setItemText(3, _translate("MainWindow", "Jsc"))
        self.comboBox_PVPTimeParam.setItemText(4, _translate("MainWindow", "Vmpp"))
        self.comboBox_PVPTimeParam.setItemText(5, _translate("MainWindow", "Jmpp"))
        self.comboBox_PVPTimeParam.setItemText(6, _translate("MainWindow", "Pmpp"))
        self.comboBox_PVPTimeParam.setItemText(7, _translate("MainWindow", "Roc"))
        self.comboBox_PVPTimeParam.setItemText(8, _translate("MainWindow", "Rsc"))
        self.comboBox_PVPTimeParam.setItemText(9, _translate("MainWindow", "HI"))
        self.checkBox_PVPTimeRelativeTime.setText(_translate("MainWindow", "RelativeTime?"))
        self.checkBox_PVPTimeBig4.setText(_translate("MainWindow", "Big4"))
        self.checkBox_PVPTimeNormal.setText(_translate("MainWindow", "Normal.?"))
        self.pushButton_PVPTimeLegend.setText(_translate("MainWindow", "Change legend"))
        self.pushButton_PVPTimePlot.setText(_translate("MainWindow", "Plot time"))
        self.groupBox_PVP.setTitle(_translate("MainWindow", "Param VS Param"))
        self.pushButton_SavePVPGraph.setText(_translate("MainWindow", "Save graph"))
        self.comboBox_PVPx.setItemText(0, _translate("MainWindow", "Eff"))
        self.comboBox_PVPx.setItemText(1, _translate("MainWindow", "FF"))
        self.comboBox_PVPx.setItemText(2, _translate("MainWindow", "Voc"))
        self.comboBox_PVPx.setItemText(3, _translate("MainWindow", "Jsc"))
        self.comboBox_PVPx.setItemText(4, _translate("MainWindow", "Vmpp"))
        self.comboBox_PVPx.setItemText(5, _translate("MainWindow", "Jmpp"))
        self.comboBox_PVPx.setItemText(6, _translate("MainWindow", "Pmpp"))
        self.comboBox_PVPx.setItemText(7, _translate("MainWindow", "Roc"))
        self.comboBox_PVPx.setItemText(8, _translate("MainWindow", "Rsc"))
        self.comboBox_PVPx.setItemText(9, _translate("MainWindow", "HI"))
        self.comboBox_PVPy.setItemText(0, _translate("MainWindow", "Eff"))
        self.comboBox_PVPy.setItemText(1, _translate("MainWindow", "FF"))
        self.comboBox_PVPy.setItemText(2, _translate("MainWindow", "Voc"))
        self.comboBox_PVPy.setItemText(3, _translate("MainWindow", "Jsc"))
        self.comboBox_PVPy.setItemText(4, _translate("MainWindow", "Vmpp"))
        self.comboBox_PVPy.setItemText(5, _translate("MainWindow", "Jmpp"))
        self.comboBox_PVPy.setItemText(6, _translate("MainWindow", "Pmpp"))
        self.comboBox_PVPy.setItemText(7, _translate("MainWindow", "Roc"))
        self.comboBox_PVPy.setItemText(8, _translate("MainWindow", "Rsc"))
        self.comboBox_PVPy.setItemText(9, _translate("MainWindow", "HI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TimeEvol), _translate("MainWindow", "TimeEvol"))
        self.groupBox_HistoGraph.setTitle(_translate("MainWindow", "Histogram"))
        self.pushButton_SaveHistoGraph.setText(_translate("MainWindow", "Save graph"))
        self.checkBox_HistoFit.setText(_translate("MainWindow", "Fit"))
        self.label_13.setText(_translate("MainWindow", "#bins"))
        self.comboBox_HistoType.setItemText(0, _translate("MainWindow", "bar"))
        self.comboBox_HistoType.setItemText(1, _translate("MainWindow", "barstacked"))
        self.comboBox_HistoType.setItemText(2, _translate("MainWindow", "step"))
        self.comboBox_HistoType.setItemText(3, _translate("MainWindow", "stepfilled"))
        self.comboBox_HistoScanDirect.setItemText(0, _translate("MainWindow", "OnyRev"))
        self.comboBox_HistoScanDirect.setItemText(1, _translate("MainWindow", "OnlyForw"))
        self.comboBox_HistoScanDirect.setItemText(2, _translate("MainWindow", "Bestof/pix"))
        self.comboBox_HistoScanDirect.setItemText(3, _translate("MainWindow", "Bestof/subst"))
        self.comboBox_HistoScanDirect.setItemText(4, _translate("MainWindow", "Allmeas"))
        self.comboBox_HistoParam.setItemText(0, _translate("MainWindow", "Eff"))
        self.comboBox_HistoParam.setItemText(1, _translate("MainWindow", "FF"))
        self.comboBox_HistoParam.setItemText(2, _translate("MainWindow", "Voc"))
        self.comboBox_HistoParam.setItemText(3, _translate("MainWindow", "Jsc"))
        self.comboBox_HistoParam.setItemText(4, _translate("MainWindow", "Vmpp"))
        self.comboBox_HistoParam.setItemText(5, _translate("MainWindow", "Jmpp"))
        self.comboBox_HistoParam.setItemText(6, _translate("MainWindow", "Pmpp"))
        self.comboBox_HistoParam.setItemText(7, _translate("MainWindow", "Roc"))
        self.comboBox_HistoParam.setItemText(8, _translate("MainWindow", "Rsc"))
        self.comboBox_HistoParam.setItemText(9, _translate("MainWindow", "HI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Histogram), _translate("MainWindow", "Histogram"))
        self.groupBox.setTitle(_translate("MainWindow", "Importation"))
        self.pushButton_ImportData.setText(_translate("MainWindow", "Import data"))
        self.pushButton_DeleteRows.setText(_translate("MainWindow", "Delete selected table elements"))
        self.pushButton_DefineGroup.setText(_translate("MainWindow", "Define Group"))
        self.pushButton_AutoAnalysis.setText(_translate("MainWindow", "Auto-Analysis"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Group"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sample"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Area"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ScanDirect."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Jsc"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Voc"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "FF"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Eff."))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Roc"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Rsc"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Vmpp"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Jmpp"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Pmpp"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "SunIntensity"))
        self.menuSession.setTitle(_translate("MainWindow", "Session"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_to_DB.setText(_translate("MainWindow", "Save to DB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

